### ISSUE TITLE
knetmaps new enhancements to-do list - for knetminer network view

### ISSUE THREAD

**Issue by AjitPS** [Rothamsted/knetmaps.js#25]
As discussed, we can change knetmaps (network view/ cyjs) defaults (presently just displays seed gene label with yellow highlight) to:

- [x] display labels for **all** `Gene, Biological_Process and Trait` nodes,
- [x] based on `taxid` attribute, pick from **7 colors** to highlight `gene` node `label` (seed genes labels will remain yellow as before),
- [x] fix **highlight on/off** context-menu feature (for nodes). Currently uses black as default (from `knet-builder: json export/ cyjs` plugin). Override so if `black`, instead use `lightGreen` else (for not black) use predefined `gold`/yellow color,
- [x] use new `dashed` lines for **cooccurs_with, regulates, occurs_in, has_similar_sequence, enriched_for** relations,
- [x] color new `occurs_in` relation as orange (same as published_in),
- [x] color black `xref` relation as darkGrey,
- [x] color black `associated_with` as darkGrey.

(linked to https://github.com/Rothamsted/knetminer/issues/582)

**Comment by AjitPS** [comment]
gene label blues by taxid https://github.com/Rothamsted/knetmaps.js/commit/ba18d75c0c8e05e195c477df737412fc62f1844d
